---
services:
  database:
    image: mysql:latest
    container_name: blog_app
    environment:
      MYSQL_ROOT_PASSWORD: blog_password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3306:3306"

  backend:
    image: node:18
    ports:
      - 1337:1337
    depends_on:
      - database
    volumes:
      - ./:/backend/
    command: bash -c "npm install && npm start"
    working_dir: /backend

  frontend:
    image: node:18
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - ../blog-app/:/frontend/
    command: bash -c "npm install && npm run dev"
    working_dir: /frontend

  web_server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    volumes:
      - ./web_server/nginx.conf:/etc/nginx/nginx.conf
      - ./web_server/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web_server/proxy_params.conf:/etc/nginx/proxy_params.conf:ro 
volumes:
  db_data: